#!C:\Users\User\Desktop\Для учёбы\НИУ ВШЭ (ГУ - ВШЭ)\VScode\DL2\minitorch-module-0-APieceOfHappiness\.dl2_hw1\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
